//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSURANCE
    {
        public long ASSURANCE_ID { get; set; }
        public long VEHICLE_ID { get; set; }
        public int MINISTRY_ID { get; set; }
        public string Maintenance_Type { get; set; }
        public string Insurance_Policy { get; set; }
        public string Insurance_Start_Date { get; set; }
        public string Local_Insurance_Exp_Date { get; set; }
        public long Amount { get; set; }
        public string Insurance_Company { get; set; }
        public string Comment { get; set; }
        public string Insurance_State { get; set; }
    
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
