//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRIVER()
        {
            this.MINISTRY_DRIVER = new HashSet<MINISTRY_DRIVER>();
            this.LICENSEs = new HashSet<LICENSE>();
        }
    
        public long DRIVER_ID { get; set; }
        public string Driver_Code { get; set; }
        public string Full_Name { get; set; }
        public string CNI { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Driver_Type { get; set; }
        public string Postal_code { get; set; }
        public string Email { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public string Marital_Status { get; set; }
        public string DOB { get; set; }
        public string Mother_Language { get; set; }
        public string Office_Phone { get; set; }
        public string Personnal_Phone { get; set; }
        public string Picture { get; set; }
        public string Ministry_Work { get; set; }
        public string State { get; set; }
        public string Visibility { get; set; }
        public string Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MINISTRY_DRIVER> MINISTRY_DRIVER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICENSE> LICENSEs { get; set; }
    }
}
