//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRANT_RIGHT
    {
        public long RowId { get; set; }
        public long ROLE_ID { get; set; }
        public long Menu_Code { get; set; }
        public string Access { get; set; }
        public int MINISTRY_ID { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual MINISTRY MINISTRY { get; set; }
    }
}
