//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVE_TYPE
    {
        public int LEAVE_TYPE_ID { get; set; }
        public string Leave_Type_Description { get; set; }
        public string Leave_Number { get; set; }
    }
}
