//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINISTRY_REAL_ESTATE
    {
        public int MIN_REAL_ESTATE_ID { get; set; }
        public int REAL_ESTATE_ID { get; set; }
        public int MINISTRY_ID { get; set; }
        public string Quantity { get; set; }
        public string Comment { get; set; }
    
        public virtual MINISTRY MINISTRY { get; set; }
        public virtual REAL_ESTATE REAL_ESTATE { get; set; }
    }
}
