//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINISTRY_DRIVER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MINISTRY_DRIVER()
        {
            this.LEAVEs = new HashSet<LEAVE>();
            this.CAR_CRASH = new HashSet<CAR_CRASH>();
        }
    
        public long MIN_DRIVER_ID { get; set; }
        public string Min_Driver_RegNumber { get; set; }
        public long DRIVER_ID { get; set; }
        public int MINISTRY_ID { get; set; }
        public string Position_Status { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Swaped_Vehicle { get; set; }
    
        public virtual DRIVER DRIVER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAVE> LEAVEs { get; set; }
        public virtual MINISTRY MINISTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_CRASH> CAR_CRASH { get; set; }
    }
}
