//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINISTRY
    {
        public int MINISTRY_ID { get; set; }
        public string Code_Min { get; set; }
        public string Ministry_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Postal_code { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string System_Name { get; set; }
        public string System_Email { get; set; }
        public string System_Title { get; set; }
    }
}
