//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL
    {
        public int MODEL_ID { get; set; }
        public Nullable<int> MARK_ID { get; set; }
        public string Model_Name { get; set; }
        public string Comment { get; set; }
    
        public virtual MARK MARK { get; set; }
    }
}
