//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER
    {
        public long PROVIDER_ID { get; set; }
        public string Provider_Type { get; set; }
        public string Provider_Code { get; set; }
        public string Full_Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Stat { get; set; }
        public string CNI { get; set; }
        public string DOB { get; set; }
        public string Address { get; set; }
        public string Picture { get; set; }
        public string Contract { get; set; }
        public string Saved_Date { get; set; }
        public string Deleted { get; set; }
    }
}
