//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleFleetManagment.FleetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_FUEL_SUPPLY
    {
        public long VEHICLE_FUEL_ID { get; set; }
        public long VEHICLE_ID { get; set; }
        public Nullable<int> MINISTRY_ID { get; set; }
        public string Fuel_Type { get; set; }
        public string Tank_Type { get; set; }
        public string Tank_Code { get; set; }
        public string Provider_Code { get; set; }
        public double Odometer { get; set; }
        public double Initial_Qty { get; set; }
        public double Consumed_Qty { get; set; }
        public double United_Price { get; set; }
        public double Total_Price { get; set; }
        public double Liter_100_km { get; set; }
        public string Comment { get; set; }
        public string Saved_Date { get; set; }
        public Nullable<double> Fuel_Used { get; set; }
        public string User_IP_Address { get; set; }
        public string Permission { get; set; }
        public string Deleted { get; set; }
    
        public virtual MINISTRY MINISTRY { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
